
services:
  frontend:
    build:
      context: . #/client  # Path to your Angular app
    ports:
      - "8090:80"  # Expose frontend on port 8090, mapped to port 80 inside container
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
